name: Ghost Build System - Release Binaries

on:
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install compiler (Linux only)
        if: runner.os == 'Linux'
        run: sudo apt update && sudo apt install -y build-essential

      - name: Build with Ghost
        run: python ghost/ghost-build.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os == 'Windows' && 'ghost-win' || 'ghost-linux' }}
          path: |
            ghost-build-linux
            ghost-build-windows.exe

  release:
    name: Release Binaries
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Get release tag
        id: tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Create binary release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag }}-binaries
          name: ${{ steps.tag.outputs.tag }} Binaries
          files: dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
